on: [push, pull_request, workflow_dispatch]
name: Continuous Integration
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write

jobs:
  build-only-ios:
    name: Build only (iOS)
    runs-on: macos-15
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install .NET 8.0.x
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"

      - name: Install .NET Workloads
        run: dotnet workload install ios

      - name: Use Xcode 16.4
        run: sudo xcode-select -switch /Applications/Xcode_16.4.app

      - name: Build
        run: dotnet build -c Debug osu.iOS.slnf
